version: '2'

services:
  pritunl:
    image: 'buker/k8s-pritunl:${TAG}'
    privileged: true
    ports:
      - '80:80'
      - '443:443'
      - '1194:1194/udp'
      - '1194:1194/tcp'
    volumes:
      - 'pritunl_data:/var/lib/pritunl'
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=${MONGODB_USER} 
      - MONGODB_PASS=${MONGODB_PASS}
    volumes:
      - 'mongodb_data:/data/db'
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/stdout

volumes:
  mongodb_data:
    driver: local
  pritunl_data:
    driver: local
